### ISSUE TITLE
Do not ever delete jobs

### ISSUE THREAD

**Issue by mileszs** [indyhackers/indyhackers.org#81]
(Just stop showing them.)

The problem is that today we delete jobs after they've been on the board for 60 days. This is short-sighted. For one, we don't allow the user to instead "re-up", or something along those lines. Secondly, frankly, having the data of what companies have posted what jobs over time would be useful to the organization. For instance, it would be nice to be able to survey the posters to help further the development of the job board!

The solution is to implement soft-delete. I mean, that's what I think, anyway. This also means we should make the `admin:sweep_jobs` rake task a no-op, and ultimately disabled Heroku scheduler.

**Comment by rreinhardt9** [comment]
@mileszs what would you think about switching this on it's head, and instead of soft deleting or hard deleting we only show jobs in the listing that are "active". We could define being active as having a published_at date less than 60 days ago and not in the future. `scope :active -> { published.where("jobs.published_at >= ?", 60.days.ago) }`.

- If the published_at date is in the future, it would not show up in the jobs listing because it's not active yet.
- If the published_at date is more than 60 days ago, it's no longer shown because it's expired

This might open the door for us to re-up a job simply by publishing it again in the future. Although, then you kind of muddy the waters on how many views a particular posting received. So maybe if we wanted something like that in the future we could "duplicate" an old job in order to "create" a new one (that represents a new unique posting of that job).

I think there is currently a bug that will prevent a job from being posted the full 60 days unless it has a published_at date the same day it was submitted (created) #107 By no longer deleting stale jobs and only showing active ones, we would solve that issue as well.

What are your thoughts?
